#!/bin/bash
set -euo pipefail

# "Stage 2" configuration.  This script (indirectly) calls itself because some actions
# it needs to take need to occur in a different context.
# See the code near the end of this file to better understand this section.
stage2="${1:-}"
if [ "$stage2" = "--config-tunnel-net" ] || \
   [ "$stage2" = "--config-share-net" ] || \
   [ "$stage2" = "--config-isolate-net" ] ; then

    tmp_dir="${2:-}"
    if [ -z "$tmp_dir" ] ; then
        echo >&2 "$0: temporary data directory not specified for stage-2 configuration"
        exit 1
    fi
    shift 2

    # Open file descriptors for bwrap to read contents from
    # (bwrap does not take file paths directly)
    exec 137< "$tmp_dir/bwrap_args"
    exec 138< "$tmp_dir/passwd"
    exec 139< "$tmp_dir/group"
    exec 140< "$tmp_dir/machine-id"

    if [ "$stage2" = "--config-tunnel-net" ] ; then

        exec 141< "$tmp_dir/hosts"
        exec 142< "$tmp_dir/resolv.conf"

        # Apply nft rules passed in by the user, if any
        [[ ! -L "$tmp_dir/main.nft" ]] || nft -o -f "$tmp_dir/main.nft" 

    elif [ "$stage2" = "--config-isolate-net" ] ; then

        exec 141< "$tmp_dir/hosts"

        # Activate loopback interface and enable unprivileged ping
        ip link set lo up
        sysctl -q -w net.ipv4.ping_group_range="0 0"

    fi

    # Unlink temporary files early.  They will be automated purged
    # by the kernel once bwrap is finished reading them.
    rm -f "$tmp_dir"/*

    # Continue with sandboxing: 
    # this script will always pass in "bwrap" and its arguments
    exec "$@"
fi

# Defaults
env_file=
filter_file=
etc_dir=
dry_run=0
host_name=
is_openssh=0
share_net=0
tunnel_net=0
tcp_ports=
udp_ports=
become_root=0
work_manifest_files=()

bwrap_path="${AGENT_BWRAP_PATH:-"$(which bwrap 2>/dev/null || true)"}"
pasta_path="${AGENT_PASTA_PATH:-"$(which pasta 2>/dev/null || true)"}"

usage() {
    cat <<EOF
Usage: $0 [OPTIONS] [--] [program args...]

Positional arguments:

  program                    Path to target program to run in the sandbox;
                             If omitted, runs the log-in shell
  args                       Zero or more arguments to the target program

Options:

 Users and environments:

  -E, --env-file PATH        File with NAME=VALUE settings for env. variables
  -r, --root                 Become root (UID=0) inside the sandbox
  -S, --openssh              Adapt for OpenSSH's sshd, e.g. env-variable settings

 Filesystem mounting:

  -e, --etc-dir PATH         Point at a directory containing a template for 
                             /etc inside the sandbox
  -w, --work-manifest PATH   File listing "working directories/files" 
                             that are to be mounted read/write

 Network:

  -f, --filter-file PATH     Apply rules to the sandbox with the Linux 
                             kernel's "nftables" (NetFilter).  This option may 
                             only be specified together with --tunnel-net.
  -h, --host-name NAME       Override the name of the host in the sandbox
  -N, --share-net            Share network with the host
  -n, --tunnel-net           Sandbox tunnels network communications to host

  --tcp-ports SPEC           TCP ports from host to forward into sandbox.
                             SPEC is as described in pasta's manual page.
                             Default is "none": no ports forwarded.
  --udp-ports SPEC           UDP ports from host to forward into sandbox.
                             SPEC is as described in pasta's manual page.
                             Default is "none": no ports forwarded.

 Sandbox construction:

  -d, --dry-run              Just show the commands to execute, but not
                             create the sandbox or run the target program

  --bwrap-path               Path to "bwrap" program used for sandboxing
                             Defaults to the env. variable AGENT_BWRAP_PATH
                             if defined, else "bwrap" as found on PATH
  --pasta-path               Path to "pasta" program used for network tunnelling.
                             Defaults to the env. variable AGENT_PASTA_PATH, 
                             if defined, else "pasta" as found on PATH

  --help                     Display this help text
  --version                  Display version of this software

EOF
    exit 0
}

# Call GNU getopt to canonicalize arguments.
# -o defines short options ('h' takes no arg, 'n:' takes a required arg)
# -l defines long options ('help' takes no arg, 'name:' takes a required arg)
short_options="de:E:f:h:SNnrw:"
long_options="help,version,dry-run,etc-dir:,env-file:,filter-file:,host-name:,openssh,share-net,tunnel-net,root,work-manifest:,tcp-ports:,udp-ports:,bwrap-path:,pasta-path:"
parsed=$(getopt -o "$short_options" --long "$long_options" -n "$0" -- "$@")
if [ $? -ne 0 ]; then
    exit 1
fi

# Re-assign positional parameters using eval to safely retain quotes/spaces
eval set -- "$parsed"

# Parse options until reaching the '--' separator
while true; do
    case "$1" in
        --help)          usage;;
        --version)       echo "Version 1.0.0"; exit 0;;
        -e|--etc-dir)     etc_dir="$2"; shift 2;;
        -d|--dry-run)     dry_run=1; shift;;
        -E|--env-file)    env_file="$2"; shift 2;;
        -f|--filter-file) filter_file="$2"; shift 2;;
        -h|--host-name)   host_name="$2"; shift 2;;
        -S|--openssh)     is_openssh=1; shift;;
        -N|--share-net)   share_net=1; shift;;
        -n|--tunnel-net)  tunnel_net=1; shift;;
        -w|--work-manifest) work_manifest_files+=("$2"); shift 2;;
        -r|--root)        become_root=1; shift;;
        --tcp-ports)      tcp_ports="$2"; shift 2;;
        --udp-ports)      udp_ports="$2"; shift 2;;
        --bwrap-path)     bwrap_path="$2"; shift 2;;
        --pasta-path)     pasta_path="$2"; shift 2;;
        --)
            shift
            break
            ;;
        *)
            echo >&2 "$0: internal argument parsing error"
            exit 1
            ;;
    esac
done

if (( share_net + tunnel_net > 1 )) ; then
    echo >&2 "$0: cannot specify both --share-net and --tunnel-net"
    exit 1
fi


# Config files:
#   If there are symbolic links, the links will be resolved 
#   immediately, but not within sub-directories.
#   Mounted read-only.
config_whitelist=(
  "$HOME/.gitconfig"
  "$HOME/.vimrc"

  # Networking
  /etc/networks
  /etc/protocols
  /etc/services
  /etc/rpc
  
  # TLS/SSL Certificates
  /etc/ssl/
  /etc/pki/
  /etc/ca-certificates/
  
  # Dynamic Linker
  /etc/ld.so.conf
  /etc/ld.so.conf.d/
  /etc/ld.so.cache

  # Other configuration
  /etc/alternatives/
  /etc/localtime
  /etc/man_db.conf

  # Static information
  /etc/os-release
)

bwrap_args=(
  --die-with-parent
  
  --unshare-user 
  --unshare-ipc 
  --unshare-pid 
  --unshare-cgroup-try
)

# Enable networking if requested.
# (For "tunnelling", bwrap inherits not the host's network namespace 
#  but the network namespace set up by pasta, below.)
if [ "$share_net" -ne 0 ] ; then
    # And therefore we must disallow overriding the sandbox's machine name,
    # because any new name would be inconsistent with the existing files above.
    if [ -n "${host_name}" ] ; then
        echo >&2 "$0: cannot override host name of sandbox when sharing existing network"
        exit 1
    fi
else
    # Set host name for sandbox
    bwrap_args+=( --unshare-uts )
    if [ -n "${host_name}" ] ; then
        bwrap_args+=( --hostname "${host_name}" )
    fi
fi

# We explicitly set bwrap to become the target *real* user & group, to make
# the user/group ownership of mounted files in the home directory match (usually).
#
# Also, when running bwrap in pasta, pasta always becomes root in the user namespace
# it creates, so we need to override it in bwrap to our desired UID/GID
if [ "$become_root" -ne 0 ] ; then
    target_uid=0
    target_gid=0
else
    target_uid="$(id -ru)"
    target_gid="$(id -rg)"
fi
bwrap_args+=( --uid $target_uid --gid $target_gid )

# Get home directory for the real target user from the system user database.
#
# Since we are making a sandbox we do not want to propagate random enviroment variables
# to the sandbox target, and that includes $HOME.  Also if the effective user is
# different from the real user, $HOME may point to home of the effective user.
# 
# FIXME we need to parse environment variables first so we don't override the user's setting
# on the command line
real_home="$(getent passwd "$(id -ru)" | cut -d: -f6)"
bwrap_args+=( --clearenv 
              --setenv HOME "$real_home" )

bwrap_args+=( 
  --proc /proc
  --dev /dev

  --mqueue /dev/mqueue

  # Set up /tmp directory
  --perms 1777 --tmpfs /tmp

  # Set up /run directory
  --tmpfs /run
  --dir /run/lock 

  # Set up /var directory structure
  --dir /var
  --symlink ../run /var/run
  --symlink ../run/lock /var/lock
  --symlink ../tmp /var/tmp
  --tmpfs /var/cache

  # Create container for dynamically-generated /etc files
  --dir /etc

  # Set up base home directory that is writable since many tools/apps depend on that.
  # Note that except for explicitly bind-mounted "work" directories, changes 
  # will not be persisted outside the sandbox.
  --tmpfs "$real_home"
)



# System files: 
#   If there are symbolic links, the links will not be resolved 
#   immediately, but will be retained and carried over into the sandbox.
#   Mounted read-only.
system_whitelist=(
    /usr
    /bin
    /lib
    /lib64
    /opt
)

# Load plain text file consisting of lines into an array
parse_manifest()
{
    manifest_file="$1"
    manifest_rel_dir="$(dirname "$(realpath "$1")")"

    # Output results into an array reference passed in by the caller
    declare -n out_array="$2"
    
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Trim leading whitespace
        line="${line#"${line%%[![:space:]]*}"}"
    
        # Skip empty lines and comment lines
        [[ -z "$line" || "$line" =~ ^# ]] && continue
        
        # If path is relative then make relative to that of manifest
        if ! [[ "$line" =~ ^/ ]] ; then 
            line="$manifest_rel_dir/$line"
        fi
        
        out_array+=( "$line" )
    
    done < "$manifest_file"
}

for path in "${system_whitelist[@]}"; do
    if [ -L "$path" ] ; then
        link_target="$(readlink -n "$path")"
        bwrap_args+=( --symlink "$link_target" "$path" )
    else
        bwrap_args+=( --ro-bind-try "$path" "$path" )
    fi
done

for path in "${config_whitelist[@]}"; do
    bwrap_args+=( --ro-bind-try "$path" "$path" )
done

declare -a work_whitelist
for path in "${work_manifest_files[@]}" ; do
    parse_manifest "$path" work_whitelist
done

# Work directories:
#   These are mounted read-write.
for path in "${work_whitelist[@]}"; do
    bwrap_args+=( --bind-try "$path" "$path" )
done

if [ -n "$etc_dir" ] ; then
    shopt -s nullglob
    for path in "$etc_dir"/*; do 
        dest="/etc/$(basename "$path")"
        if [ -L "$path" ] ; then
            link_target="$(readlink -n "$path")"
            bwrap_args+=( --symlink "$link_target" "$dest" )
        else
            bwrap_args+=( --ro-bind-try "$path" "$dest" )
        fi
    done
fi


# Propagate TERM like ssh does
bwrap_args+=( --setenv TERM "$TERM" )



if [ -n "${env_file}" ] ; then

    if [ "$is_openssh" -ne 0 ] ; then
        # sshd will not pass the environment variables it is invoked with to
        # the sandbox user's log-in session.
        #
        # Instead, just bind-mount the file into $HOME/.ssh/environment assuming 
        # "PermitUserEnvironment yes" has been set in /etc/ssh/sshd_config.
        bwrap_args+=( --ro-bind "${env_file}" "$HOME/.ssh/environment" )
    else
        # Create --setenv arguments for bwrap for each NAME=VALUE pair
        while IFS= read -r line || [[ -n "$line" ]]; do
            # Trim leading/trailing whitespace
            line="${line#"${line%%[![:space:]]*}"}"
            line="${line%"${line##*[![:space:]]}"}"
    
            # Skip empty lines and comment lines
            [[ -z "$line" || "$line" =~ ^# ]] && continue
    
            # Parse KEY=VALUE using regex (ensures valid bash variable name format)
            if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
                key="${BASH_REMATCH[1]}"
                val="${BASH_REMATCH[2]}"
            fi
    
            bwrap_args+=("--setenv" "$key" "$val")
        done < "$env_file"
    fi
fi



if [ "$dry_run" -ne 0 ] ; then
    echo "$bwrap_path" "${bwrap_args[@]}" -- "$@"
    exit 0
fi

# Check for existence of bwrap
if [ ! -x "$bwrap_path" ] ; then
    echo >&2 "$0: the bwrap program is required to run but could not be found"
    exit 2
fi

if [ "$tunnel_net" -eq 0 ] ; then
    if [ -n "$filter_file" ] ; then
        echo >&2 "$0: --filter-file can only be specified when tunnelling network"
        exit 1
    fi
    if [ -n "$tcp_ports" ] ; then 
        echo >&2 "$0: --tcp-ports can only be specified when tunnelling network"
        exit 1
    fi
    if [ -n "$udp_ports" ] ; then 
        echo >&2 "$0: --udp-ports can only be specified when tunnelling network"
        exit 1
    fi
fi

# Prepare to write temporary files for data to pass to bwrap.
#
# When using pasta (for --tunnel-net), we cannot pass file descriptors to bwrap because 
# pasta calls close_range(2) at start-up --- as a deliberate security measure to 
# prevent leaks into containers, but breaks our use case.
#
# But even when not using pasta, we have multiple files we want to dynamically generate
# into the sandbox, and it is easier to use a common code path.
tmp_dir="$(mktemp -d -t "$(basename "$0")-XXXXXX")"
trap 'rm -rf "$tmp_dir"' exit

# Get log-in shell for the real target user.
# Default to executing that if no program was specified on the command line.
login_shell="$(getent passwd "$target_uid" | cut -d: -f7)"
if [ $# -eq 0 ]; then
    set -- "$login_shell" "-l"
fi

# Generate /etc/passwd and /etc/group dynamically, based the target user/group
etc_passwd_entries=()
etc_group_entries=()
if [ "$target_uid" -eq 0 ] ; then
    etc_passwd_entries+=( "root:x:0:0:Super User:${real_home}:${login_shell}" )
    etc_group_entries+=( "root:x:0:" )
else
    target_user_name="$(id -run)"
    target_group_name="$(id -rgn)"
    etc_passwd_entries+=( "root:x:0:0:Super User:/:/bin/sh"
                          "${target_user_name}:x:${target_uid}:${target_gid}:Normal User:${real_home}:${login_shell}" )
    etc_group_entries+=( "root:x:0:"
                         "${target_group_name}:x:${target_gid}:" )
fi
etc_passwd_entries+=( "nobody:x:65534:65534:Unmapped User:/:/usr/sbin/nologin" )
etc_group_entries+=( "nobody:x:65534:" )
printf '%s\n' "${etc_passwd_entries[@]}" > "$tmp_dir/passwd"
printf '%s\n' "${etc_group_entries[@]}" > "$tmp_dir/group"
bwrap_args+=( --perms 444 --file 138 /etc/passwd )
bwrap_args+=( --perms 444 --file 139 /etc/group )

# Generate /etc/machine-id
tr -d '-' < /proc/sys/kernel/random/uuid > "$tmp_dir/machine-id"
bwrap_args+=( --perms 444 --file 140 /etc/machine-id )

commit_bwrap_args()
{
    # Seal the root filesystem to be read-only after all modifications
    bwrap_args+=( --remount-ro / )

    # Write arguments to temporary file
    printf '%s\0' "${bwrap_args[@]}" > "$tmp_dir/bwrap_args"
}

if [ "$tunnel_net" -ne 0 ] ; then

    # Check for existence of pasta
    if [ ! -x "$pasta_path" ] ; then
        echo >&2 "$0: the pasta program is required for --tunnel-net but could not be found"
        exit 2
    fi

    if [ -z "${host_name}" ] ; then 
        host_name="$(/bin/hostname)"
        host_name="${host_name:-agent-sandbox}"
        bwrap_args+=( --hostname ${host_name} )
    fi

    if [ "${host_name}" = "gateway" ] ; then
        echo >&2 "$0: sandbox cannot be named 'gateway'"
        exit 2
    fi

    # Let the inner script know about the NFT filter file passed in by the user.
    #
    # Ideally we would check validity first, so that the sandbox is not started half-way 
    # if there turns out to be an error in the filter rules, but unfortunately even
    # checking the file requires root privileges (without the current user namespace).
    if [ -n "$filter_file" ] ; then
        if [ ! -e "$filter_file" ] ; then
            echo >&2 "$0: nft filter file $filter_file does not exist"
            exit 2
        fi
        ln -s "$(realpath "$filter_file")" "$tmp_dir/main.nft" 
    fi

    # Must drop this capability if the target user in the sandbox is root,
    # who would be able to manipulate firewall rules otherwise, defeating the security
    bwrap_args+=( --cap-drop CAP_NET_ADMIN )

    # Generate /etc/resolv.conf pointing to pasta's DNS forwarder
    cat > "$tmp_dir/resolv.conf" <<EOF
nameserver 169.254.0.1
EOF

    # Generate /etc/hosts containing the host name that was set.
    # It must be consistent with pasta's setting of IP addresses, below.
    #
    # For IPv4 we use a link-local address.
    # For IPv6, link-local addresses may require scope/interface IDs in some
    # instances; we avoid the complication by using a Unique Local Address instead.
    cat > "$tmp_dir/hosts" <<EOF
127.0.0.1   localhost
::1         localhost 
169.254.0.2 ${host_name}
fd00::2     ${host_name}
169.254.0.1 gateway
fd00::1     gateway
EOF

    bwrap_args+=( --perms 444 --file 141 /etc/hosts )
    bwrap_args+=( --perms 444 --file 142 /etc/resolv.conf )
    commit_bwrap_args

    # Launch bwrap wrapped in pasta.
    # pasta creates the network namespace that does Layer-4 tunnelling.
    #
    # Although bwrap does allow some other process (pasta) to alter the configuration
    # the network namespace it creates to add tunnelling, in practice that feature
    # does not work, because:
    #
    #   (a) It gets clumsy to synchronize the different phases of execution 
    #       of bwrap with external programs, especially in a shell script.
    #
    #   (b) A network namespace cannot be configured without the SYS_CAP_ADMIN
    #       capability within the parent user namespace.  But for a *unprivileged* 
    #       sandbox, SYS_CAP_ADMIN can only be retained if the sandbox's UID is 0 
    #       (root; as set by the --uid option to bwrap).  The Linux kernel has a hard
    #       security restriction that unprivileged users on the host cannot create
    #       multiple users in new user namespaces (unless SETUID helpers are used).
    #
    #       So, for an unprivileged user, if the sandbox's UID is set to non-zero,
    #       the ability to configure the network namespace is permanently sealed off.
    #
    #       If you have strace log what pasta is doiing, you will see that if it is 
    #       asked to modify a network namespace with no UID=0 in its containing user 
    #       namespace, the system call to switch into the network namespace, 
    #       setns(net_ns_fd, CLONE_NEWNET), will always fail.
    #
    # The solution is to have pasta create its own "throw-away" user namespace with 
    # UID=0 inside so it can configure a new network namespace with tunnelling.
    # Then when it forks and executes bwrap, bwrap automatically inherits that network 
    # namespace avoiding the failure with setns(net_ns_fd, CLONE_NEWNET).  
    #
    # bwrap will then proceed to create its own user namespace with the UID set to
    # non-zero (optionally).
    "$pasta_path" \
        --address 169.254.0.2/16 --gateway 169.254.0.1 --dns-forward 169.254.0.1 \
        --address fd00::2/64 --gateway fd00::1 \
        --tcp-ns "${tcp_ports:-none}" --udp-ns "${udp_ports:-none}" \
        --config-net --ns-ifname sandbox_tap --no-dhcp -- \
        /bin/bash "$0" --config-tunnel-net "$tmp_dir" \
            "$bwrap_path" --args 137 "$@"

elif [ "$share_net" -ne 0 ] ; then

    # When the sandbox is sharing the host's network, 
    # import the host's /etc/hosts and /etc/resolv.conf
    bwrap_args+=( --ro-bind-try /etc/hosts /etc/hosts
                  --ro-bind-try /etc/resolv.conf /etc/resolv.conf )
    commit_bwrap_args

    # Exec bwrap in sub-shell so that: 
    # (a) the name of this script still appears in the process tree
    # (b) file descriptors are closed exactly when bwrap is finished with them
    /bin/bash "$0" --config-share-net "$tmp_dir" \
        "$bwrap_path" --args 137 "$@"

else

    # When the sandbox has no network connectivity, 
    # generate /etc/hosts with only localhost in it
    cat > "$tmp_dir/hosts" <<EOF
127.0.0.1   localhost ${host_name}
::1         localhost ${host_name}
EOF

    bwrap_args+=( --perms 444 --file 141 /etc/hosts )
    commit_bwrap_args

    # If bwrap is asked to "unshare" the network namespace, it does no set-up
    # whatsoever and that means the loopback interface is not even up.
    # Also, unprivileged pinging is not allowed.  That is not good if the 
    # sandboxed program wants to bring up local testing servers.  
    #
    # We cannot set up the network once inside bwrap, because
    # we do not have the privileges to do so if UID != 0.
    #
    # We must do the set up *outside* bwrap and then let it inherit the
    # newly set-up network namespace, just like what happens when we 
    # use "pasta" to implement --tunnel-net, above.
    #
    # Flags to "unshare":
    #   -U: create throw-away user namespace
    #   -r: maps to fake root there
    #   -n: creates network namespace
    unshare -Urn /bin/bash "$0" --config-isolate-net "$tmp_dir" \
        "$bwrap_path" --args 137 "$@"

fi

