# Without this option, something like "ping -6 localhost" gives an error:
# "Address family for hostname not supported" if the IPv6 address is listed after
# the IPv4 address in /etc/hosts; or vice versa "ping -4 localhost" fails when
# the IPv6 address appear first.
multi on
